//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCprod.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_f_commodity
    {
        public decimal com_ID { get; set; }
        public Nullable<decimal> com_price { get; set; }
        public Nullable<decimal> com_belong { get; set; }
        public string com_name { get; set; }
        public string com_number { get; set; }
        public Nullable<decimal> com_postage { get; set; }
        public string com_content { get; set; }
        public Nullable<int> com_state { get; set; }
        public Nullable<System.DateTime> com_starttime { get; set; }
        public Nullable<System.DateTime> com_saletime { get; set; }
        public Nullable<decimal> shop_ID { get; set; }
        public Nullable<bool> isdel { get; set; }
        public string comment { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public string option5 { get; set; }
    }
}
