//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCprod.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_basic_users
    {
        public decimal userid { get; set; }
        public string userphone { get; set; }
        public string userpwd { get; set; }
        public string exname { get; set; }
        public string username { get; set; }
        public string idnum { get; set; }
        public string shopid { get; set; }
        public Nullable<System.DateTime> jointime { get; set; }
        public string usercode { get; set; }
        public string useraddr { get; set; }
        public string userQQ { get; set; }
        public Nullable<bool> isDel { get; set; }
        public string comment { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public string option5 { get; set; }
    }
}
