//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCprod.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCtecanEntities : DbContext
    {
        public NCtecanEntities()
            : base("name=NCtecanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dl_basic_users> dl_basic_users { get; set; }
        public DbSet<sys_function> sys_function { get; set; }
        public DbSet<sys_role> sys_role { get; set; }
        public DbSet<sys_role_function> sys_role_function { get; set; }
        public DbSet<sys_user_role> sys_user_role { get; set; }
        public DbSet<t_f_adress> t_f_adress { get; set; }
        public DbSet<t_f_area> t_f_area { get; set; }
        public DbSet<t_f_cart> t_f_cart { get; set; }
        public DbSet<t_f_collect> t_f_collect { get; set; }
        public DbSet<t_f_commodity> t_f_commodity { get; set; }
        public DbSet<t_f_order> t_f_order { get; set; }
        public DbSet<t_f_shops> t_f_shops { get; set; }
        public DbSet<t_x_logistics> t_x_logistics { get; set; }
        public DbSet<t_x_logistics_state> t_x_logistics_state { get; set; }
    }
}
