//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCprod.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_function
    {
        public decimal fid { get; set; }
        public Nullable<int> pid { get; set; }
        public string function { get; set; }
        public string title { get; set; }
        public string control { get; set; }
        public string functionname { get; set; }
        public string parameters { get; set; }
        public Nullable<decimal> order { get; set; }
        public Nullable<decimal> level { get; set; }
        public string url { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public string option5 { get; set; }
    }
}
