//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCprod.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_f_cart
    {
        public decimal cart_ID { get; set; }
        public Nullable<decimal> cons_ID { get; set; }
        public Nullable<decimal> coms_ID { get; set; }
        public Nullable<decimal> coms_num { get; set; }
        public Nullable<bool> isdel { get; set; }
        public Nullable<System.DateTime> happendate { get; set; }
        public string comment { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public string option5 { get; set; }
    }
}
